embedding_size: 64
feat_embed_dim: 64

n_mm_layers: 1
n_layers: 2
knn_k: 10
mm_image_weight: [0.1, 0.2]
aggr_mode: 'add'
learning_rate: [0.0001]
reg_weight: [0.01, 0.001, 0.0001]

weight_size: [64, 64]

lambda_coeff: 0.9

n_ui_layers: [2, 3, 4]
dropout: 0.0
decay_base: 0.9
decay_weight: [0.9, 0.95, 0.99]
weight_decay: [0, 1e-6, 1e-5]

hyper_parameters: ["n_ui_layers", "mm_image_weight", "reg_weight", "learning_rate", "weight_decay", "decay_weight"]
